server:
  port: 9999
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"
  client:
    service-url:
      defaultZone: "http://discoveryservice:8761/eureka"