server:
  port: 9999
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  instance:
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"
    prefer-ip-address: true
  client:
    service-url:
#      defaultZone: "http://discoveryservice:8761/eureka"
      defaultZone: "http://18.224.3.178:8761/eureka"
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
